### ISSUE TITLE
关于商店无法卖出物品

### ISSUE THREAD

**Issue by DRVictoryhaohai** [ToiletMC/Issues#1]
/商店系统商店中任何商品都无法出售但可以买入且其他人都出现了同种问题
![MK~Z76M(TB8V3R7RQPIMBV](https://user-images.githubusercontent.com/67898556/86988720-7beef080-c1cb-11ea-8d4e-9b2f89315ea4.png)
![5Z$MFXZ(E W5%@ 5SR~Y$ O](https://user-images.githubusercontent.com/67898556/86988722-7d201d80-c1cb-11ea-9ec4-5f933934d626.png)
![KY1}HD L3@7V~E CBYQX9 9](https://user-images.githubusercontent.com/67898556/86988724-7db8b400-c1cb-11ea-868b-2988c02c4b50.png)

**Comment by XXY233** [comment]
已经通知开发者，等待修复...

**Comment by XXY233** [comment]
已解决！谢谢你的报告

**Comment by lushangkan** [comment]
> 已解决！谢谢你的报告

请把等待解决的标签移除,谢谢!
