### ISSUE TITLE
商店出售出现错误

### ISSUE THREAD

**Issue by YuShenLiu03** [ToiletMC/Issues#4]
卖不了东西

能卖就好

![QQ图片20210216180433](https://user-images.githubusercontent.com/63281706/108048007-7ae74100-7081-11eb-9532-e80da1d7c050.png)
![QQ图片20210216180442](https://user-images.githubusercontent.com/63281706/108048011-7c186e00-7081-11eb-95c6-8d11e595f2ab.png)

**Comment by XXY233** [comment]
问题已修复，感谢您的反馈。祝您生活愉快！
